### PR TITLE
Fix: script doesn't run well on non-English system

### PR DESCRIPTION
**Pull request by SleepyBag**

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Oh, my system is in English so I've never noticed. What exactly doesn't run correctly? Also, are we talking about Chinese characters or any other language?

**Comment by marioortizmanero** [comment]
Thanks a bunch for the PR! I never thought of this.

It's a small thing, but can you please move it under the config variables (OSD, INC, MAX_VOL, etc)? These should always be at the top so that it's more intuitive to configure, IMO.

**Comment by SleepyBag** [comment]
Thank you for your reply. It is moved down now.

**Comment by marioortizmanero** [comment]
Just merged it, thanks again :)

**Pull request merged**
