### PR TITLE
Add --listen-timeout-secs

### LINKED ISSUE #70: No longer updates every time volume changes
When changing my volume, a visual update is painfully slow and (as I have a keyboard with a volume wheel, and thus have it set up so that volume goes up by only one each time), it makes it really difficult to set a precise volume now without going really slowly to wait for it to update. Below is running the same command through the terminal, and you can see that it is skipping a bunch, where as pre 3.0.0 updated at every change.
image
Is this intended behaviour? I really hope not, or I'll have to stick to the outdated version.

### PR DESCRIPTION
**Pull request by marioortizmanero**
Fixes #70. @thennothinghappened, please let me know if this solves your issue. You may be interested in this feature as well, @Aerion.

### CODE REVIEW

**Comment by marioortizmanero** [comment]
Should we also modify the default value? Or is it good enough at 100 ms? I did change it on my own setup to 50 ms, but not sure what the default should be.

Going from 100 ms to 50 ms on my system increases the maximum load when spamming a lot from 1.9% to 2.6% (very roughly). The difference is somewhat noticeable visually. I would say it's good enough for my case, since for this test I spammed it as much as I could, which isn't a realistic use-case.

Shall we use 50 ms? Also, is the documentation for the new flag ok? Too many details?

**Comment by Aerion** [comment]
Documentation looks good. Users probably expect quick responsiveness to the changes.
What do you think of changing it to 50ms, but adding a section in the README indicating what to do if the CPU usage is too high for the user?

**Comment by marioortizmanero** [comment]
Sounds good! I'll do that and release a new version.

**Comment by marioortizmanero** [comment]
I've just added a FAQ section, which I wanted to do for a long time anyway. That includes a question about CPU usage and insufficient latency.

**Pull request merged**
